---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synergychat-api-pvc
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
